/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Vehicle struct {
	Color string `json:"color,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	IdS string `json:"id_s,omitempty"`
	OptionCodes string `json:"option_codes,omitempty"`
	VehicleId string `json:"vehicle_id,omitempty"`
	Vin string `json:"vin,omitempty"`
	Tokens []string `json:"tokens,omitempty"`
	State string `json:"state,omitempty"`
}
