/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NavigationRequestRequest struct {
	// Do not change
	Type_ string `json:"type,omitempty"`
	Value *NavigationRequestRequestValue `json:"value,omitempty"`
	// Do not change
	Locale string `json:"locale,omitempty"`
	// Unix timestamp
	TimestampMs string `json:"timestamp_ms,omitempty"`
}
