/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GuiState struct {
	GuiDistanceUnits string `json:"gui_distance_units,omitempty"`
	GuiTemperatureUnits string `json:"gui_temperature_units,omitempty"`
	GuiChargeRateUnits string `json:"gui_charge_rate_units,omitempty"`
	Gui24HourTime bool `json:"gui_24_hour_time,omitempty"`
	GuiRangeDisplay string `json:"gui_range_display,omitempty"`
	Timestamp float32 `json:"timestamp,omitempty"`
}
