/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VehicleStateSoftwareUpdate struct {
	ExpectedDurationSec int32 `json:"expected_duration_sec,omitempty"`
	Status string `json:"status,omitempty"`
	DownloadPerc int32 `json:"download_perc,omitempty"`
	InstallPerc int32 `json:"install_perc,omitempty"`
	Version string `json:"version,omitempty"`
}
