/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type State string

// List of State
const (
	OPEN_State State = "open"
	CLOSE_State State = "close"
	COMFORT_State State = "comfort"
	VENT_State State = "vent"
	MOVE_State State = "move"
)
