/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClimateState struct {
	InsideTemp float64 `json:"inside_temp,omitempty"`
	OutsideTemp float64 `json:"outside_temp,omitempty"`
	DriverTempSetting float64 `json:"driver_temp_setting,omitempty"`
	PassengerTempSetting float64 `json:"passenger_temp_setting,omitempty"`
	LeftTempDirection int32 `json:"left_temp_direction,omitempty"`
	RightTempDirection int32 `json:"right_temp_direction,omitempty"`
	IsFrontDefrosterOn bool `json:"is_front_defroster_on,omitempty"`
	IsRearDefrosterOn bool `json:"is_rear_defroster_on,omitempty"`
	FanStatus int32 `json:"fan_status,omitempty"`
	IsClimateOn bool `json:"is_climate_on,omitempty"`
	MinAvailTemp int32 `json:"min_avail_temp,omitempty"`
	MaxAvailTemp int32 `json:"max_avail_temp,omitempty"`
	SeatHeaterLeft string `json:"seat_heater_left,omitempty"`
	SeatHeaterRight string `json:"seat_heater_right,omitempty"`
	SeatHeaterRearLeft string `json:"seat_heater_rear_left,omitempty"`
	SeatHeaterRearRight string `json:"seat_heater_rear_right,omitempty"`
	SeatHeaterRearCenter string `json:"seat_heater_rear_center,omitempty"`
	SeatHeaterRearRightBack string `json:"seat_heater_rear_right_back,omitempty"`
	SeatHeaterRearLeftBack string `json:"seat_heater_rear_left_back,omitempty"`
	BatteryHeater bool `json:"battery_heater,omitempty"`
	BatteryHeaterNoPower bool `json:"battery_heater_no_power,omitempty"`
	SteeringWheelHeater bool `json:"steering_wheel_heater,omitempty"`
	WiperBladeHeater bool `json:"wiper_blade_heater,omitempty"`
	SideMirrorHeaters bool `json:"side_mirror_heaters,omitempty"`
	IsPreconditioning bool `json:"is_preconditioning,omitempty"`
	SmartPreconditioning bool `json:"smart_preconditioning,omitempty"`
	IsAutoConditioningOn bool `json:"is_auto_conditioning_on,omitempty"`
	DefrostMode int32 `json:"defrost_mode,omitempty"`
	Timestamp float32 `json:"timestamp,omitempty"`
}
