/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateAccessTokenResponse struct {
	// 
	AccessToken string `json:"access_token"`
	// 
	TokenType string `json:"token_type"`
	// 
	ExpiresIn int32 `json:"expires_in"`
	// 
	CreatedAt int32 `json:"created_at"`
	// 
	RefreshToken string `json:"refresh_token"`
}
