/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VehicleStateSpeedLimitMode struct {
	Active bool `json:"active,omitempty"`
	CurrentLimitMph float64 `json:"current_limit_mph,omitempty"`
	MaxLimitMph float64 `json:"max_limit_mph,omitempty"`
	MinLimitMph float64 `json:"min_limit_mph,omitempty"`
	PinCodeSet bool `json:"pin_code_set,omitempty"`
}
