/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SetSpeedLimitRequest struct {
	// The speed limit to set, in Miles per Hour
	LimitMph int32 `json:"limit_mph,omitempty"`
}
