/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateAccessTokenRequest struct {
	// The type of oAuth grant. \"password\" or \"refresh_token\"
	GrantType string `json:"grant_type,omitempty"`
	// The oAuth client ID
	ClientId string `json:"client_id,omitempty"`
	// The oAuth client secret
	ClientSecret string `json:"client_secret,omitempty"`
	// The email for my.teslamotors.com. Only used with \"password\" grant type.
	Email string `json:"email,omitempty"`
	// The password for my.teslamotors.com. Only used with \"password\" grant type.
	Password string `json:"password,omitempty"`
	// A refresh token from a previous CreateAccessTokenResponse
	RefreshToken string `json:"refresh_token,omitempty"`
}
