/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MovePanoRoofRequest struct {
	// The desired state of the panoramic roof. The approximate percent open values for each state are `open` = 100%, `close` = 0%, `comfort` = 80%, and `vent` = ~15%
	State string `json:"state,omitempty"`
	// The percentage to move the roof to.
	Percent float64 `json:"percent,omitempty"`
}
