/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VehicleState struct {
	ApiVersion int32 `json:"api_version,omitempty"`
	AutoparkState string `json:"autopark_state,omitempty"`
	AutoparkStateV2 string `json:"autopark_state_v2,omitempty"`
	AutoparkStyle string `json:"autopark_style,omitempty"`
	CalendarSupported bool `json:"calendar_supported,omitempty"`
	CarVersion string `json:"car_version,omitempty"`
	CenterDisplayState int32 `json:"center_display_state,omitempty"`
	Df int32 `json:"df,omitempty"`
	Dr int32 `json:"dr,omitempty"`
	Ft int32 `json:"ft,omitempty"`
	HomelinkNearby bool `json:"homelink_nearby,omitempty"`
	LastAutoparkError string `json:"last_autopark_error,omitempty"`
	Locked bool `json:"locked,omitempty"`
	MediaState *VehicleStateMediaState `json:"media_state,omitempty"`
	NotificationsSupported bool `json:"notifications_supported,omitempty"`
	Odometer float64 `json:"odometer,omitempty"`
	ParsedCalendarSupported bool `json:"parsed_calendar_supported,omitempty"`
	Pf int32 `json:"pf,omitempty"`
	Pr int32 `json:"pr,omitempty"`
	RemoteStart bool `json:"remote_start,omitempty"`
	RemoteStartSupported bool `json:"remote_start_supported,omitempty"`
	Rt int32 `json:"rt,omitempty"`
	SentryMode bool `json:"sentry_mode,omitempty"`
	SoftwareUpdate *VehicleStateSoftwareUpdate `json:"software_update,omitempty"`
	SunRoofPercentOpen int32 `json:"sun_roof_percent_open,omitempty"`
	SunRoofState string `json:"sun_roof_state,omitempty"`
	Timestamp float32 `json:"timestamp,omitempty"`
	ValetMode bool `json:"valet_mode,omitempty"`
	VehicleName string `json:"vehicle_name,omitempty"`
	SpeedLimitMode *VehicleStateSpeedLimitMode `json:"speed_limit_mode,omitempty"`
	FdWindow int32 `json:"fd_window,omitempty"`
	FpWindow int32 `json:"fp_window,omitempty"`
	HomelinkDeviceCount int32 `json:"homelink_device_count,omitempty"`
	RdWindow int32 `json:"rd_window,omitempty"`
	RpWindow int32 `json:"rp_window,omitempty"`
}
