/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WakeUpResponseResponse struct {
	UserId float32 `json:"user_id,omitempty"`
	VehicleId float32 `json:"vehicle_id,omitempty"`
	Vin string `json:"vin,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	OptionCodes string `json:"option_codes,omitempty"`
	Color string `json:"color,omitempty"`
	Tokens []string `json:"tokens,omitempty"`
	State string `json:"state,omitempty"`
	InService bool `json:"in_service,omitempty"`
	Id string `json:"id,omitempty"`
	CalendarEnabled bool `json:"calendar_enabled,omitempty"`
	ApiVersion string `json:"api_version,omitempty"`
	BackseatToken string `json:"backseat_token,omitempty"`
	BackseatTokenUpdatedAt float32 `json:"backseat_token_updated_at,omitempty"`
}
