/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Supercharger struct {
	Location *DestinationChargerLocation `json:"location,omitempty"`
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
	DistanceMiles float64 `json:"distance_miles,omitempty"`
	AvailableStalls float32 `json:"available_stalls,omitempty"`
	TotalStalls float32 `json:"total_stalls,omitempty"`
	SiteClosed bool `json:"site_closed,omitempty"`
}
