/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 
type CommandResponseResponse struct {
	Result bool `json:"result,omitempty"`
	Reason string `json:"reason,omitempty"`
}
