/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ShareRequest struct {
	// Change to \"share_dest_content_coords\" if using lat/long
	Type_ string `json:"type,omitempty"`
	Value *ShareRequestValue `json:"value,omitempty"`
	// Locale this request should be treated as
	Locale string `json:"locale,omitempty"`
	// UNIX timestamp indicating when this request was sent
	Timestamp float32 `json:"timestamp,omitempty"`
}
