/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChargeState struct {
	ChargingState string `json:"charging_state,omitempty"`
	FastChargerType string `json:"fast_charger_type,omitempty"`
	FastChargerBrand string `json:"fast_charger_brand,omitempty"`
	ChargeLimitSoc int32 `json:"charge_limit_soc,omitempty"`
	ChargeLimitSocStd int32 `json:"charge_limit_soc_std,omitempty"`
	ChargeLimitSocMin int32 `json:"charge_limit_soc_min,omitempty"`
	ChargeLimitSocMax int32 `json:"charge_limit_soc_max,omitempty"`
	ChargeToMaxRange bool `json:"charge_to_max_range,omitempty"`
	MaxRangeChargeCounter int32 `json:"max_range_charge_counter,omitempty"`
	FastChargerPresent bool `json:"fast_charger_present,omitempty"`
	BatteryRange float64 `json:"battery_range,omitempty"`
	EstBatteryRange float64 `json:"est_battery_range,omitempty"`
	IdealBatteryRange float64 `json:"ideal_battery_range,omitempty"`
	BatteryLevel int32 `json:"battery_level,omitempty"`
	UsableBatteryLevel int32 `json:"usable_battery_level,omitempty"`
	ChargeEnergyAdded float64 `json:"charge_energy_added,omitempty"`
	ChargeMilesAddedRated float64 `json:"charge_miles_added_rated,omitempty"`
	ChargeMilesAddedIdeal float64 `json:"charge_miles_added_ideal,omitempty"`
	ChargerVoltage int32 `json:"charger_voltage,omitempty"`
	ChargerPilotCurrent int32 `json:"charger_pilot_current,omitempty"`
	ChargerActualCurrent int32 `json:"charger_actual_current,omitempty"`
	ChargerPower int32 `json:"charger_power,omitempty"`
	TimeToFullCharge float64 `json:"time_to_full_charge,omitempty"`
	TripCharging bool `json:"trip_charging,omitempty"`
	ChargeRate float64 `json:"charge_rate,omitempty"`
	ChargePortDoorOpen bool `json:"charge_port_door_open,omitempty"`
	ConnChargeCable string `json:"conn_charge_cable,omitempty"`
	ScheduledChargingStartTime string `json:"scheduled_charging_start_time,omitempty"`
	ScheduledChargingPending bool `json:"scheduled_charging_pending,omitempty"`
	UserChargeEnableRequest bool `json:"user_charge_enable_request,omitempty"`
	ChargeEnableRequest bool `json:"charge_enable_request,omitempty"`
	ChargerPhases int32 `json:"charger_phases,omitempty"`
	ChargePortLatch string `json:"charge_port_latch,omitempty"`
	ChargeCurrentRequest int32 `json:"charge_current_request,omitempty"`
	ChargeCurrentRequestMax int32 `json:"charge_current_request_max,omitempty"`
	ManagedChargingActive bool `json:"managed_charging_active,omitempty"`
	ManagedChargingUserCanceled bool `json:"managed_charging_user_canceled,omitempty"`
	ManagedChargingStartTime float32 `json:"managed_charging_start_time,omitempty"`
	BatteryHeaterOn bool `json:"battery_heater_on,omitempty"`
	NotEnoughPowerToHeat bool `json:"not_enough_power_to_heat,omitempty"`
	Timestamp float32 `json:"timestamp,omitempty"`
}
