/*
 * Tesla Model S JSON API
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VehicleDataResponseResponse struct {
	Color string `json:"color,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Id string `json:"id,omitempty"`
	OptionCodes string `json:"option_codes,omitempty"`
	VehicleId string `json:"vehicle_id,omitempty"`
	Vin string `json:"vin,omitempty"`
	UserId float32 `json:"user_id,omitempty"`
	Tokens []string `json:"tokens,omitempty"`
	State string `json:"state,omitempty"`
	InService bool `json:"in_service,omitempty"`
	IdS string `json:"id_s,omitempty"`
	CalendarEnabled bool `json:"calendar_enabled,omitempty"`
	BackseatToken string `json:"backseat_token,omitempty"`
	BackseatTokenUpdatedAt float32 `json:"backseat_token_updated_at,omitempty"`
	GuiSettings *GuiState `json:"gui_settings,omitempty"`
	ClimateState *ClimateState `json:"climate_state,omitempty"`
	DriveState *DriveState `json:"drive_state,omitempty"`
	VehicleState *VehicleState `json:"vehicle_state,omitempty"`
	ChargeState *ChargeState `json:"charge_state,omitempty"`
	VehicleConfig *VehicleConfig `json:"vehicle_config,omitempty"`
}
